.eslintrc.cjs, .prettierrc.cjs, .stylelintrc.cjs, package.json, pnpm-lock.yaml, src/main.tsx, tsconfig.json, vite.config.ts
=> Configures the project and installs Prettier, ESLint, Stylelint

.eslintrc.cjs, .gitignore, package.json, pnpm-lock.yaml
=> Installs and configures Storybook

package.json, pnpm-lock.yaml, src/main.tsx, src/styles/_boilerplate.scss, src/styles/_colors.scss, src/styles/_typography.scss, src/styles/index.scss
=> Sets up basic styles and variables to suit the design.

src/components/ui/card/Card.tsx, src/components/ui/card/card.module.scss, src/components/ui/card/card.stories.tsx
Write: Develop components/UI/Card
=> feat: Develop components/UI/Card

src/common/components/ui/grade/Grade.tsx, src/common/components/ui/grade/grade.module.scss, src/common/components/ui/grade/grade.stories.tsx, src/common/components/ui/tables/Tables.tsx, src/common/components/ui/tables/tables.module.scss, src/common/components/ui/tables/tables.stories.tsx, src/common/components/ui/tools/Tools.tsx, src/common/components/ui/tools/tools.module.scss, src/common/components/ui/tools/tools.stories.tsx
Write: Develop components/UI/Tables
=> feat: Develop components/UI/Tables

package.json, pnpm-lock.yaml, src/common/components/index.ts, src/common/components/ui/button/button.stories.tsx, src/common/components/ui/button/index.ts, src/common/components/ui/index.ts, src/common/components/ui/pagination/index.ts, src/common/components/ui/pagination/mainPaginationButtons/MainPaginationButtons.tsx, src/common/components/ui/pagination/pagination.stories.tsx, src/common/components/ui/select/Select.tsx, src/common/components/ui/select/index.ts, src/common/components/ui/slider/Slider.tsx, src/common/components/ui/slider/slider.module.scss, src/common/components/ui/slider/slider.stories.ts, src/common/components/ui/slider/slider.stories.tsx, src/common/components/ui/typography/Typography.tsx, src/common/components/ui/typography/index.ts
feat: add Slider component
fix: deleted extra index.ts and fix imports
=> feature/#29 feat: Develop components/UI/Slider 

src/common/components/ui/tables/Tables.tsx, src/common/components/ui/tables/grade/Grade.tsx, src/common/components/ui/tables/tools/Tools.tsx
Set forward ref for components: card, checkbox, input, tables
=> Refactor/#45 refactor: Set forward ref for components: card, checkbox, input, tables

src/common/components/ui/checkbox/Checkbox.tsx, src/common/components/ui/checkbox/checkbox.module.scss, src/common/components/ui/checkbox/checkbox.stories.tsx
Fix the type in the checkbox, add new stories, replace the label element on typography
=> Bugfix/#49 Fix the type in the checkbox, add new stories, replace the label element on typography

src/common/components/ui/input/Input.tsx, src/common/components/ui/input/input.stories.tsx, src/common/components/ui/input/useInput.tsx
Change incoming props and logic inside the useInput hook, putting logical expressions into variables, deleting an object for baseClassNames styles
=> Refactor/#55 Change props Input , move logic into separate variables

src/common/components/ui/select/Select.tsx, src/common/components/ui/slider/Slider.tsx, src/common/components/ui/tabs/Tabs.tsx, src/common/components/ui/typography/Typography.tsx
Reverts Arenelin/-flash-cards-#54
=> Revert "Feature/#44 set forward ref for components tabs select slider typography"

src/common/components/ui/card/Card.tsx, src/common/components/ui/card/card.module.scss, src/common/components/ui/card/card.stories.tsx
Replace forward ref typing for a polymorphic component, check this typing in the storybook, change styles
=> Bugfix/#57 Replace forward ref typing for a polymorphic component

src/common/components/ui/controlled/controlled-input/Controlled-input.tsx, src/common/components/ui/controlled/controlled-input/control-input.stories.tsx, src/common/components/ui/input/Input.tsx
Develop Controlled-input and storybook
=> feature/#62 feat:Develop Controlled-input and storybook

src/common/components/forms/signIn/FormSignIn.tsx, src/common/components/forms/signIn/formSignIn.module.scss, src/common/components/forms/signIn/formSignIn.stories.tsx, src/common/components/ui/button/Button.tsx, src/common/components/ui/card/Card.tsx, src/common/components/ui/typography/Typography.tsx
Develop form Sign In, component history in storybook, replace forward ref typing in polymorphic components
=> Feature/#66  Develop form Sign In, component history in storybook

src/common/components/forms/signIn/FormSignIn.tsx, src/common/components/forms/signIn/formSignIn.module.scss, src/common/components/ui/card/card.module.scss, src/common/components/ui/checkbox/checkbox.module.scss, src/common/components/ui/input/Input.tsx, src/common/components/ui/input/input.module.scss, src/common/components/ui/typography/Typography.tsx, src/common/components/ui/typography/typography.module.scss
=> Bugfix/#76 Fix style input,card,checkbox

src/common/components/ui/tables/tools/Tools.tsx
=> Bugfix/#97 fix: Fix component Tools

src/common/components/ui/slider/Slider.tsx, src/features/modals/modalDelete/ModalDelete.tsx, src/features/modals/modalDelete/modalDelete.module.scss, src/features/modals/modalDelete/modalDelete.stories.tsx
=> feature/#123 Develop ModalDelete component

src/common/components/tables/tables.module.scss, src/common/components/tables/ui/containerName/ContainerName.tsx, src/common/components/tables/ui/containerName/containerName.module.scss, src/features/decks/ui/decksList/ui/tableDecksList/TableDecksList.tsx
Fix component TableDeckList, add ContainerName
=> bugfix/#135  fix: Fix component TableDeckList, add ContainerName

package.json, pnpm-lock.yaml, src/app/api/appApi.ts, src/common/components/toastNotification/ToastNotification.tsx, src/common/components/toastNotification/toastNotification.stories.tsx, src/common/types/typesAuth.ts, src/common/utils/zodSchema.ts, src/features/auth/ui/signUp/FormSignUp.tsx, src/features/layout/Layout.tsx, src/features/modals/modalDeck/ModalDeck.tsx, src/router/Router.tsx, src/router/ui/pagesAuth/PageSignUp.tsx, src/router/ui/pagesAuth/PagesAuth.tsx
=> Feature/#133 Add Registration Logic

src/common/components/tables/tables.module.scss, src/common/components/tables/ui/buttonSort/ButtonSort.tsx, src/common/components/tables/ui/containerImgText/containerImageText.module.scss, src/common/enums/enums.ts, src/common/hooks/useDebounce.ts, src/common/types/typesDecks.ts, src/features/decks/api/decksApi.ts, src/features/decks/ui/deckById/DeckById.tsx, src/features/decks/ui/deckById/lib/useCardsList.ts, src/features/decks/ui/deckById/ui/tableCardsList/TableCardsList.tsx, src/features/decks/ui/decks.module.scss, src/features/layout/layout.module.scss, src/router/Router.tsx, src/router/ui/pageDeckById/PageDeckById.tsx
=> Feature/#139 Add a card GET request

src/common/components/modal/modal.module.scss, src/common/components/select/Select.tsx, src/common/components/select/select.module.scss, src/features/modals/ModalCard/ModalCard.tsx, src/features/modals/ModalCard/modalCard.module.scss, src/features/modals/ModalCard/modalCard.stories.tsx, src/features/modals/modalDeck/modalDeck.module.scss, src/features/modals/modalDeck/modalDeck.stories.tsx
=> Feature/#143 Add Component CreateCard

vercel.json
=> chore: configures automatic updates Storybook

src/common/components/tables/ui/tablesHeaderSort/TablesHeaderSort.tsx
=> fix: fix focus visible
